### ISSUE TITLE
Dying kernel

### ISSUE THREAD

**Issue by csevast** [ryanpepper/tcl_kernel#10]
I followed the installation instructions but kernel cannot be started. 

The following is the jupyter output:

Traceback (most recent call last):
  File "C:\Program_Files\Miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program_Files\Miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program_Files\Miniconda3\lib\site-packages\tcl_kernel\__main__.py", line 2, in <module>
    from .kernel import TclKernel
  File "C:\Program_Files\Miniconda3\lib\site-packages\tcl_kernel\kernel.py", line 10, in <module>
    libc = ctypes.CDLL(None)
  File "C:\Program_Files\Miniconda3\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None
[JupyterQtConsoleApp] WARNING | KernelRestarter: restart failed
[JupyterQtConsoleApp] WARNING | kernel died: 3.012035846710205

The following is the kernel.json file:
{
    "argv": [
        "C:\\Program_Files\\Miniconda3\\python.exe",
        "-m",
        "tcl_kernel",
        "-f",
        "{connection_file}"
    ],
    "codemirror_mode": {"name": "text/x-tcl", "version": 2},
    "display_name": "Tcl",
    "file_extension": ".tcl",
    "language": "Tcl",
    "mimetype": "text/x-tcl"
}

I thank you on advance.

**Comment by rpep** [comment]
Hi @csevast,

The kernel has never supported Tcl on Windows, because I never tested it on this platform as I don't have access to a Windows machine. If you want to make a pull request to add support I'm happy to merge it, but I don't have time or the resources to work on this anymore as I'm not often working with Tcl often.

The way it works is a bit of a trick really; Tcl gets bundled with Python as a module for some basic GUI support. Because of that we can basically pass commands to a Tcl shell through Python without any messing around with the subprocess module. I can't really remember the reason it didn't work on Windows, but looking at the code I can see I had to do something strange to get it to work on macOS. It might be a simple fix.

Thanks,
Ryan

**Comment by csevast** [comment]
Dear Ryan,

I thank you for your response. Unfortunately Tcl programming is not in my
priorities. Thus, I cannot afford time for supporting your project for the
Windows combatibilities issues. I hope that somebody else will be more
willing than me to help.

Sincerely,
Christos Sevastiadis






Electrical Engineering Diploma
Electroacoustics PhD
Laboratory Teacher

School of Electrical and Computer Engineering
Aristotle University of Thessaloniki
University Campus
Thessaloniki, 541 24
Greece

mob. +30 6977447820
tel. +30 2310996317
